### ISSUE TITLE
Add user ID for logged in user as body class

### ISSUE THREAD

**Issue by ijy** [lindseydiloreto/craft-cpbodyclasses#1]
As a feature request, would it be possible to add the User ID for the logged in user as a body class? This can be useful for hiding entries on a per user and per entry basis.

**Comment by lindseydiloreto** [comment]
Great idea! I'll add this when I get a chance. 👍

**Comment by ijy** [comment]
Sweet! If you could include individual entry permissions along with it then we'll call it a day. ;)

**Comment by lindseydiloreto** [comment]
Lol, one step at a time. 😄

**Comment by lindseydiloreto** [comment]
This is done.

As of [2.1.0](https://github.com/doublesecretagency/craft-cpbodyclasses/blob/v2/CHANGELOG.md#210---2018-05-10), it's now possible to access a `userid-*` class on every page of the CP. This class will reflect the ID of the currently logged in user.

There is also now a `profileid-*` class, which only exists when editing a user's profile. Similarly, it reflects the ID of the user profile being viewed.

**Comment by ijy** [comment]
Woop woop! Thanks Lindsey. Like the nice addition of `profileid` on the user profile page.
