### ISSUE TITLE
Add a flag for the current "Site"

### ISSUE THREAD

**Issue by lindseydiloreto** [lindseydiloreto/craft-cpbodyclasses#2]
If the user switches between sites when editing an entry, the body class should adjust accordingly.

**Comment by lindseydiloreto** [comment]
Also for the entry index page.

**Comment by lindseydiloreto** [comment]
This is done. As of [2.1.0](https://github.com/doublesecretagency/craft-cpbodyclasses/blob/v2/CHANGELOG.md#210---2018-05-10), there is now an `entriessite-*` class which exists when you are editing a particular entry.

Unfortunately, the same class is not possible on the entry index page. On the index page, the URL does not change when switching between sites. It could potentially be done via some complex JS, but it's not something I was able to add at this time.

**Comment by KatieMFritz** [comment]
Thanks for adding this! If you're able to return to the more complex problem (of flagging pages based on site, even when the URL doesn't reflect it) in the future, I'd be very excited.

**Comment by KatieMFritz** [comment]
Current workaround:
```js
var header = document.getElementById('header')
var site1Handle = 'Sustainable Agriculture and Food Systems Minor'
var site2Handle = 'EFFS Staging'
var site1Class = 'entriessite-safs'
var site2Class = 'entriessite-effs'

if ( header.innerHTML.toString().indexOf(site1Handle + '</div>') > -1 ) {
  document.body.classList.add(site1Class)
  document.body.classList.remove(site2Class)
}

if ( header.innerHTML.toString().indexOf(site2Handle + '</div>') > -1 ) {
  document.body.classList.add(site2Class)
  document.body.classList.remove(site1Class)
}
```
