### ISSUE TITLE
Missing cp body class since updating to Craft 3.2.*

### ISSUE THREAD

**Issue by jonleverrier** [lindseydiloreto/craft-cpbodyclasses#3]
First off, I just wanted to say how much I appreciate this plugin! 

I've noticed that since upgrading to Craft 3.2.3, the following body class is no longer applied when creating a new un-saved entry:

```
.currentpage-entries-myexamplesection-new
```

I'm guessing the reason for this is because in Craft 3.2.3 the URL segments have changed. When you create a new entry it's immediately saved as a draft?

If `.currentpage-entries-myexamplesection-new` isn't possible because of the Craft 3.2 updates, how about checking if the URL contains any parameters, such as `?draftId`?

It would be great to have this class added back in somehow. I have a set of checkboxes that don't need to be displayed until the entry is saved, so the `.currentpage-entries-myexamplesection-new` class was a perfect fit for this!

Craft: 3.2.3
Control Panel Body Classes: 2.1.0

**Comment by lindseydiloreto** [comment]
This should be fixed now. Update to the latest, and let me know if that does the trick for you!

**Comment by jonleverrier** [comment]
Brilliant! Works perfectly.
